### ISSUE TITLE
documentation shows wrong unit default

### ISSUE THREAD

**Issue by meznak** [seunomosowon/SA-geodistance#1]
The readme [indicates](https://github.com/seunomosowon/SA-geodistance#key-concepts-for-sa-geodistance) that `miles=true` is default, but actual results returned use km unless `miles=false `is specified.

```
| geodistance latfield=lat longfield=lon output_field=gd_distance_miles miles=true
| geodistance latfield=lat longfield=lon output_field=gd_distance_km_maybe
```

![image](https://user-images.githubusercontent.com/1106662/32860976-8f285fde-ca10-11e7-903f-4b50524f21eb.png)

First row: 2975mi is just over 4788, plus or minus rounding errors.

**Comment by seunomosowon** [comment]
Thanks Nathan,

I’ll update the code to use miles this weekend..

Best regards,
Oluwaseun Remi-Omosowon

**Comment by seunomosowon** [comment]
Actually, I'll just update the documentation to say it's in Km. I just checked, and you're right. If miles is not specified, it's set to false. Thanks a lot. I'll make updates this weekend.
